name = "PlotlyExtensionsHelper"
uuid = "a7e57fc7-3548-4021-90c3-ac0e175068b1"
authors = ["Alberto Mengali <disberd@gmail.com> and contributors"]
version = "0.2.0"

[deps]

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlutoPlotly = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"

[extensions]
PlotlyBaseExtensionModule = "PlotlyBase"
PlotlyJSExtensionModule = "PlotlyJS"
PlutoPlotlyExtensionModule = "PlutoPlotly"

[compat]
PlotlyBase = "0.8"
PlotlyJS = "0.18"
PlutoPlotly = "0.4, 0.5"
julia = "1.9"
